name: Update Spotify Status
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-spotify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tthn0/Spotify-Readme@master
        with:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
